//Context Protyectos
export const FORMULARIO_PROYECTO = "Formulario_PROYECTO";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINANDO_PROYECTO = "ELIMINANDO_PROYECTO";
export const PROYECTO_ERROR = "PROYECTO_ERROR";

//context Tareas
export const OBTENER_TAREAS = "OBTENER_TAREAS";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const VALIDAR_TAREA = "VALIDAR_TAREA";
export const ELIMINANDO_TAREA = "ELIMINANDO_TAREA";
export const MODIFICAR_ESTADO = "MODIFICAR_ESTADO";
export const TAREA_ACTUAL = "TAREA_ACTUAL";
export const ACTUALIZANDO_TAREA = "ACTUALIZANDO_TAREA";

//context alertas
export const MOSTRAR_ALERTA ="MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

//context autentificacion 
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
