export const FORMULARIO_PROYECTO = "Formulario_PROYECTO";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINANDO_PROYECTO = "ELIMINANDO_PROYECTO";


export const OBTENER_TAREAS = "OBTENER_TAREAS";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const VALIDAR_TAREA = "VALIDAR_TAREA";
export const ELIMINANDO_TAREA = "ELIMINANDO_TAREA";
export const MODIFICAR_ESTADO = "MODIFICAR_ESTADO";
export const TAREA_ACTUAL = "TAREA_ACTUAL";
export const ACTUALIZANDO_TAREA = "ACTUALIZANDO_TAREA";