export const FORMULARIO_PROYECTO = "Formulario_PROYECTO";
export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINANDO_PROYECTO = "ELIMINANDO_PROYECTO";

